const CONFIG = {
    introTitle: 'Hú!',
    introDesc: `Ngủ chưa,bảo cái này😁`,
    btnIntro: 'Chưa.',
    title: 'Thế kể chuyện đi😙',
    desc: 'Đọc văn tế như t hôm trước cũng được ',
    btnYes: 'Chờ tý.',
    btnNo: 'Không,Đi ngủ',
    question:'Kể,hát hay đọc thế :>>',
    btnReply: 'Gửi ở đây :>>',
    reply: ':D',
    mess: 'Triển luôn đi nhá :>>',
    messDesc: 'Nhanhhhhhh nhá :>>.',
    btnAccept: 'Đây má',
    messLink: 'https://www.facebook.com/profile.php?id=100040031167499'}
