const CONFIG = {
    introTitle: 'Hú!',
    introDesc: `Đi ngủ chưa lè,chưa thì bấm dưới này :>>`,
    btnIntro: 'Đây.',
    title: 'Chỗ này tính viweets j đó nma đang demo nên k biết viết j',
    desc: '=)) ',
    btnYes: 'Rồi =)).',
    btnNo: 'Không nha má =))',
    question:'Chết dở nhá =)):>>',
    btnReply: 'Thôi học tiếp đi,đoạn đầu á tính để nhạc chúc bé ngủ ngon =)):>>',
    reply: ':D',
    mess: 'hí hí:>>',
    messDesc: 'Nt tiếp cũng đc hhahah:>>.',
    btnAccept: '=))',
    messLink: 'https://www.facebook.com/profile.php?id=100040031167499'}
